#!/bin/bash
emojis=("☀️ " "🌞" "⛅️" "🌻" "🕶️" "🌤️")
random_index=$((RANDOM % ${#emojis[@]}))
afplay /Users/jgolden1/script-util/rooster-crow.wav
echo "Good morning! ${emojis[$random_index]}"
today=$(date "+%d")
this_month=$(date "+%m")
daily_scriptures=
case $today in
  01|08|15|22|29)
    daily_scriptures=book_of_mormon
    ;;
  07|14|21|28)
    daily_scriptures=doctrine_and_covenants
    ;;
  03|09|19|25)
    daily_scriptures=come_follow_me
    ;;
  06|13|31)
    daily_scriptures=pearl_of_great_price
    ;;
  10|20|30)
    daily_scriptures=old_testament
    ;;
  02|12|23|27)
    daily_scriptures=new_testament
    ;;
  04|16|17|26)
    daily_scriptures=church_history
    ;;
  05|11|18|24)
    daily_scriptures=24o_general_conference
    ;;
  *)
    echo "daily scripture for today's date $today not found"
    ;;
esac
vim ~/symbolic-links/rules ~/symbolic-links/happy-journal ~/symbolic-links/revelation_weekly ~/symbolic-links/$daily_scriptures ~/symbolic-links/rules
