#!/bin/bash
pod=${pod:-u}
i=1
docker ps | sed '1d' | awk '{ print $11 }' | xargs -p -I {} docker stop {}

container_name=${container_name:-util}
host_port=${host_port:-2223}

if [[ $pod == "s" ]]; then
  container_name="shofixti"
  host_port=2221
elif [[ $pod == "c" ]]; then
  container_name="chmmr"
  host_port=2222
else
  container_name="util"
  host_port=2223
fi

echo "running docker container $container_name"
if [[ ! "$(docker volume ls -q | grep $container_name)" ]]; then 
  echo "creating docker volume for $container_name"
  docker volume create $container_name
fi

docker run --rm -p ${host_port}:22 -v ${container_name}:/data --name $container_name -it util
